version: "3"

services:
    api:
        build:
            context: "../bytepit-api"
        ports:
            - "8000:80"
        depends_on:
            - database
        environment:
            - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
            - SECRET_KEY=${SECRET_KEY}
            - RAPID_API_KEY=${RAPID_API_KEY}
            - BLOB_STORAGE_CONNECTION_STRING=${BLOB_STORAGE_CONNECTION_STRING}
            - BLOB_STORAGE_CONTAINER_NAME=${BLOB_STORAGE_CONTAINER_NAME}
            - COMMUNICATION_SERVICES_CONNECTION_STRING=${COMMUNICATION_SERVICES_CONNECTION_STRING}
            - UI_URL=${UI_URL}
    database:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5450:5432"
        volumes:
            - ./database:/var/lib/postgresql/data
