version: "3"

services:
    api:
        build:
            context: "../bytepit-api"
        ports:
            - "8000:80"
        depends_on:
            - database
        environment:
            - DB_CONNECTION_STRING=host=database dbname=db user=postgres password=postgres
            - SECRET_KEY=5ce3b19d23543100e7be58f39c430a8dfb1b4584fec88283583515b05481cdf4
            - RAPID_API_KEY=672635c1ccmsh0127f8b5a277f05p1b59ffjsnb02aef9f2c98
            - BLOB_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=bytepitstorageaccount;AccountKey=STW6NC26wOXcmVpFgDYeKaC2d9O6NWaYeiTP5lG1HRFNpcZILym8FQtXL6tWgp43N4VwEzNytW0i+AStdcuiuA==;EndpointSuffix=core.windows.net
            - BLOB_STORAGE_CONTAINER_NAME=tests-dir
            - COMMUNICATION_SERVICES_CONNECTION_STRING=endpoint=https://bypit-email.europe.communication.azure.com/;accesskey=B+X+DVh9MAZ0a5AXtMWlGjTobTGRc1FAY/9tiySC9x+ZjRBGK8O1NEULwLkVGU25IPT84RFRRO1lYIR2bkDo3A==

    database:
        image: postgres
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5450:5432"
        volumes:
            - ./database:/var/lib/postgresql/data
